### ISSUE TITLE
EXOS Core not working on Windows

### ISSUE THREAD

**Issue by erseco** [exoeconomy/EXOS-Core#4]
Hello, I'm trying to set a wallet on Windows and there are some errors, is impossible to view the right menú (screenshot 1), and if you go to "wallet" window and come back to "dashboard" the window is showed as the screenshot 2

Both errors are in Windows 7 and Windows 10 with wallet 1.0.15 and 1.0.16

Screenshot 1:
<img width="1260" alt="Captura de pantalla 2021-03-24 a las 8 17 26" src="https://user-images.githubusercontent.com/1876752/112277459-ac06f280-8c79-11eb-9fda-2334598d31d0.png">

Screenshot2:
<img width="1274" alt="Captura de pantalla 2021-03-24 a las 8 17 46" src="https://user-images.githubusercontent.com/1876752/112277439-a6a9a800-8c79-11eb-8c2a-832bd92d7b93.png">

**Comment by turcol** [comment]
@erseco thanks for reporting the bug. 

Close your wallet, and open the Windows File Manager, and erase all the files under %appdata%/exoscore, and open your wallet. You should be ready to go.

**Comment by erseco** [comment]
It worked like a charm.

Thanks @turcol
